apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'vote'
        static_configs:
          - targets: ['vote:5000']
      - job_name: 'result'
        static_configs:
          - targets: ['vote:5001']
      - job_name: 'db'
        static_configs:
          - targets: ['vote:5432']
      - job_name: 'redis'
        static_configs:
          - targets: ['vote:6379']

